[package]
name = "fast-version-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.18"
litrs = "0.2.3"
fast-version-core = { path = "../fast-version-core" }
